// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: extension.proto

package hiddifyrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtensionResponseType int32

const (
	ExtensionResponseType_NOTHING     ExtensionResponseType = 0
	ExtensionResponseType_UPDATE_UI   ExtensionResponseType = 1
	ExtensionResponseType_SHOW_DIALOG ExtensionResponseType = 2
	ExtensionResponseType_END         ExtensionResponseType = 3
)

// Enum value maps for ExtensionResponseType.
var (
	ExtensionResponseType_name = map[int32]string{
		0: "NOTHING",
		1: "UPDATE_UI",
		2: "SHOW_DIALOG",
		3: "END",
	}
	ExtensionResponseType_value = map[string]int32{
		"NOTHING":     0,
		"UPDATE_UI":   1,
		"SHOW_DIALOG": 2,
		"END":         3,
	}
)

func (x ExtensionResponseType) Enum() *ExtensionResponseType {
	p := new(ExtensionResponseType)
	*p = x
	return p
}

func (x ExtensionResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExtensionResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_extension_proto_enumTypes[0].Descriptor()
}

func (ExtensionResponseType) Type() protoreflect.EnumType {
	return &file_extension_proto_enumTypes[0]
}

func (x ExtensionResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExtensionResponseType.Descriptor instead.
func (ExtensionResponseType) EnumDescriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

type ExtensionActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionId   string                 `protobuf:"bytes,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Code          ResponseCode           `protobuf:"varint,2,opt,name=code,proto3,enum=hiddifyrpc.ResponseCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionActionResult) Reset() {
	*x = ExtensionActionResult{}
	mi := &file_extension_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionActionResult) ProtoMessage() {}

func (x *ExtensionActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionActionResult.ProtoReflect.Descriptor instead.
func (*ExtensionActionResult) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{0}
}

func (x *ExtensionActionResult) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *ExtensionActionResult) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_OK
}

func (x *ExtensionActionResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExtensionList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Extensions    []*Extension           `protobuf:"bytes,1,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionList) Reset() {
	*x = ExtensionList{}
	mi := &file_extension_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionList) ProtoMessage() {}

func (x *ExtensionList) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionList.ProtoReflect.Descriptor instead.
func (*ExtensionList) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{1}
}

func (x *ExtensionList) GetExtensions() []*Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

type EditExtensionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionId   string                 `protobuf:"bytes,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Enable        bool                   `protobuf:"varint,2,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditExtensionRequest) Reset() {
	*x = EditExtensionRequest{}
	mi := &file_extension_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditExtensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditExtensionRequest) ProtoMessage() {}

func (x *EditExtensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditExtensionRequest.ProtoReflect.Descriptor instead.
func (*EditExtensionRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{2}
}

func (x *EditExtensionRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *EditExtensionRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type Extension struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Enable        bool                   `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Extension) Reset() {
	*x = Extension{}
	mi := &file_extension_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Extension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Extension) ProtoMessage() {}

func (x *Extension) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Extension.ProtoReflect.Descriptor instead.
func (*Extension) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{3}
}

func (x *Extension) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Extension) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Extension) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Extension) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type ExtensionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionId   string                 `protobuf:"bytes,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Data          map[string]string      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionRequest) Reset() {
	*x = ExtensionRequest{}
	mi := &file_extension_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionRequest) ProtoMessage() {}

func (x *ExtensionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionRequest.ProtoReflect.Descriptor instead.
func (*ExtensionRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{4}
}

func (x *ExtensionRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *ExtensionRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type SendExtensionDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExtensionId   string                 `protobuf:"bytes,1,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	Button        string                 `protobuf:"bytes,2,opt,name=button,proto3" json:"button,omitempty"`
	Data          map[string]string      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendExtensionDataRequest) Reset() {
	*x = SendExtensionDataRequest{}
	mi := &file_extension_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendExtensionDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendExtensionDataRequest) ProtoMessage() {}

func (x *SendExtensionDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendExtensionDataRequest.ProtoReflect.Descriptor instead.
func (*SendExtensionDataRequest) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{5}
}

func (x *SendExtensionDataRequest) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *SendExtensionDataRequest) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

func (x *SendExtensionDataRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExtensionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ExtensionResponseType  `protobuf:"varint,1,opt,name=type,proto3,enum=hiddifyrpc.ExtensionResponseType" json:"type,omitempty"`
	ExtensionId   string                 `protobuf:"bytes,2,opt,name=extension_id,json=extensionId,proto3" json:"extension_id,omitempty"`
	JsonUi        string                 `protobuf:"bytes,3,opt,name=json_ui,json=jsonUi,proto3" json:"json_ui,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtensionResponse) Reset() {
	*x = ExtensionResponse{}
	mi := &file_extension_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtensionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtensionResponse) ProtoMessage() {}

func (x *ExtensionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_extension_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtensionResponse.ProtoReflect.Descriptor instead.
func (*ExtensionResponse) Descriptor() ([]byte, []int) {
	return file_extension_proto_rawDescGZIP(), []int{6}
}

func (x *ExtensionResponse) GetType() ExtensionResponseType {
	if x != nil {
		return x.Type
	}
	return ExtensionResponseType_NOTHING
}

func (x *ExtensionResponse) GetExtensionId() string {
	if x != nil {
		return x.ExtensionId
	}
	return ""
}

func (x *ExtensionResponse) GetJsonUi() string {
	if x != nil {
		return x.JsonUi
	}
	return ""
}

var File_extension_proto protoreflect.FileDescriptor

const file_extension_proto_rawDesc = "" +
	"\n" +
	"\x0fextension.proto\x12\n" +
	"hiddifyrpc\x1a\n" +
	"base.proto\"\x82\x01\n" +
	"\x15ExtensionActionResult\x12!\n" +
	"\fextension_id\x18\x01 \x01(\tR\vextensionId\x12,\n" +
	"\x04code\x18\x02 \x01(\x0e2\x18.hiddifyrpc.ResponseCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"F\n" +
	"\rExtensionList\x125\n" +
	"\n" +
	"extensions\x18\x01 \x03(\v2\x15.hiddifyrpc.ExtensionR\n" +
	"extensions\"Q\n" +
	"\x14EditExtensionRequest\x12!\n" +
	"\fextension_id\x18\x01 \x01(\tR\vextensionId\x12\x16\n" +
	"\x06enable\x18\x02 \x01(\bR\x06enable\"k\n" +
	"\tExtension\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06enable\x18\x04 \x01(\bR\x06enable\"\xaa\x01\n" +
	"\x10ExtensionRequest\x12!\n" +
	"\fextension_id\x18\x01 \x01(\tR\vextensionId\x12:\n" +
	"\x04data\x18\x02 \x03(\v2&.hiddifyrpc.ExtensionRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd2\x01\n" +
	"\x18SendExtensionDataRequest\x12!\n" +
	"\fextension_id\x18\x01 \x01(\tR\vextensionId\x12\x16\n" +
	"\x06button\x18\x02 \x01(\tR\x06button\x12B\n" +
	"\x04data\x18\x03 \x03(\v2..hiddifyrpc.SendExtensionDataRequest.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x01\n" +
	"\x11ExtensionResponse\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.hiddifyrpc.ExtensionResponseTypeR\x04type\x12!\n" +
	"\fextension_id\x18\x02 \x01(\tR\vextensionId\x12\x17\n" +
	"\ajson_ui\x18\x03 \x01(\tR\x06jsonUi*M\n" +
	"\x15ExtensionResponseType\x12\v\n" +
	"\aNOTHING\x10\x00\x12\r\n" +
	"\tUPDATE_UI\x10\x01\x12\x0f\n" +
	"\vSHOW_DIALOG\x10\x02\x12\a\n" +
	"\x03END\x10\x032\xed\x03\n" +
	"\x14ExtensionHostService\x12@\n" +
	"\x0eListExtensions\x12\x11.hiddifyrpc.Empty\x1a\x19.hiddifyrpc.ExtensionList\"\x00\x12J\n" +
	"\aConnect\x12\x1c.hiddifyrpc.ExtensionRequest\x1a\x1d.hiddifyrpc.ExtensionResponse\"\x000\x01\x12V\n" +
	"\rEditExtension\x12 .hiddifyrpc.EditExtensionRequest\x1a!.hiddifyrpc.ExtensionActionResult\"\x00\x12W\n" +
	"\n" +
	"SubmitForm\x12$.hiddifyrpc.SendExtensionDataRequest\x1a!.hiddifyrpc.ExtensionActionResult\"\x00\x12J\n" +
	"\x05Close\x12\x1c.hiddifyrpc.ExtensionRequest\x1a!.hiddifyrpc.ExtensionActionResult\"\x00\x12J\n" +
	"\x05GetUI\x12\x1c.hiddifyrpc.ExtensionRequest\x1a!.hiddifyrpc.ExtensionActionResult\"\x00B\x0eZ\f./hiddifyrpcb\x06proto3"

var (
	file_extension_proto_rawDescOnce sync.Once
	file_extension_proto_rawDescData []byte
)

func file_extension_proto_rawDescGZIP() []byte {
	file_extension_proto_rawDescOnce.Do(func() {
		file_extension_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)))
	})
	return file_extension_proto_rawDescData
}

var file_extension_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_extension_proto_goTypes = []any{
	(ExtensionResponseType)(0),       // 0: hiddifyrpc.ExtensionResponseType
	(*ExtensionActionResult)(nil),    // 1: hiddifyrpc.ExtensionActionResult
	(*ExtensionList)(nil),            // 2: hiddifyrpc.ExtensionList
	(*EditExtensionRequest)(nil),     // 3: hiddifyrpc.EditExtensionRequest
	(*Extension)(nil),                // 4: hiddifyrpc.Extension
	(*ExtensionRequest)(nil),         // 5: hiddifyrpc.ExtensionRequest
	(*SendExtensionDataRequest)(nil), // 6: hiddifyrpc.SendExtensionDataRequest
	(*ExtensionResponse)(nil),        // 7: hiddifyrpc.ExtensionResponse
	nil,                              // 8: hiddifyrpc.ExtensionRequest.DataEntry
	nil,                              // 9: hiddifyrpc.SendExtensionDataRequest.DataEntry
	(ResponseCode)(0),                // 10: hiddifyrpc.ResponseCode
	(*Empty)(nil),                    // 11: hiddifyrpc.Empty
}
var file_extension_proto_depIdxs = []int32{
	10, // 0: hiddifyrpc.ExtensionActionResult.code:type_name -> hiddifyrpc.ResponseCode
	4,  // 1: hiddifyrpc.ExtensionList.extensions:type_name -> hiddifyrpc.Extension
	8,  // 2: hiddifyrpc.ExtensionRequest.data:type_name -> hiddifyrpc.ExtensionRequest.DataEntry
	9,  // 3: hiddifyrpc.SendExtensionDataRequest.data:type_name -> hiddifyrpc.SendExtensionDataRequest.DataEntry
	0,  // 4: hiddifyrpc.ExtensionResponse.type:type_name -> hiddifyrpc.ExtensionResponseType
	11, // 5: hiddifyrpc.ExtensionHostService.ListExtensions:input_type -> hiddifyrpc.Empty
	5,  // 6: hiddifyrpc.ExtensionHostService.Connect:input_type -> hiddifyrpc.ExtensionRequest
	3,  // 7: hiddifyrpc.ExtensionHostService.EditExtension:input_type -> hiddifyrpc.EditExtensionRequest
	6,  // 8: hiddifyrpc.ExtensionHostService.SubmitForm:input_type -> hiddifyrpc.SendExtensionDataRequest
	5,  // 9: hiddifyrpc.ExtensionHostService.Close:input_type -> hiddifyrpc.ExtensionRequest
	5,  // 10: hiddifyrpc.ExtensionHostService.GetUI:input_type -> hiddifyrpc.ExtensionRequest
	2,  // 11: hiddifyrpc.ExtensionHostService.ListExtensions:output_type -> hiddifyrpc.ExtensionList
	7,  // 12: hiddifyrpc.ExtensionHostService.Connect:output_type -> hiddifyrpc.ExtensionResponse
	1,  // 13: hiddifyrpc.ExtensionHostService.EditExtension:output_type -> hiddifyrpc.ExtensionActionResult
	1,  // 14: hiddifyrpc.ExtensionHostService.SubmitForm:output_type -> hiddifyrpc.ExtensionActionResult
	1,  // 15: hiddifyrpc.ExtensionHostService.Close:output_type -> hiddifyrpc.ExtensionActionResult
	1,  // 16: hiddifyrpc.ExtensionHostService.GetUI:output_type -> hiddifyrpc.ExtensionActionResult
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_extension_proto_init() }
func file_extension_proto_init() {
	if File_extension_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extension_proto_rawDesc), len(file_extension_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_extension_proto_goTypes,
		DependencyIndexes: file_extension_proto_depIdxs,
		EnumInfos:         file_extension_proto_enumTypes,
		MessageInfos:      file_extension_proto_msgTypes,
	}.Build()
	File_extension_proto = out.File
	file_extension_proto_goTypes = nil
	file_extension_proto_depIdxs = nil
}
