// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.1
// source: hiddify.proto

package hiddifyrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoreState int32

const (
	CoreState_STOPPED  CoreState = 0
	CoreState_STARTING CoreState = 1
	CoreState_STARTED  CoreState = 2
	CoreState_STOPPING CoreState = 3
)

// Enum value maps for CoreState.
var (
	CoreState_name = map[int32]string{
		0: "STOPPED",
		1: "STARTING",
		2: "STARTED",
		3: "STOPPING",
	}
	CoreState_value = map[string]int32{
		"STOPPED":  0,
		"STARTING": 1,
		"STARTED":  2,
		"STOPPING": 3,
	}
)

func (x CoreState) Enum() *CoreState {
	p := new(CoreState)
	*p = x
	return p
}

func (x CoreState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreState) Descriptor() protoreflect.EnumDescriptor {
	return file_hiddify_proto_enumTypes[0].Descriptor()
}

func (CoreState) Type() protoreflect.EnumType {
	return &file_hiddify_proto_enumTypes[0]
}

func (x CoreState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoreState.Descriptor instead.
func (CoreState) EnumDescriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_EMPTY                 MessageType = 0
	MessageType_EMPTY_CONFIGURATION   MessageType = 1
	MessageType_START_COMMAND_SERVER  MessageType = 2
	MessageType_CREATE_SERVICE        MessageType = 3
	MessageType_START_SERVICE         MessageType = 4
	MessageType_UNEXPECTED_ERROR      MessageType = 5
	MessageType_ALREADY_STARTED       MessageType = 6
	MessageType_ALREADY_STOPPED       MessageType = 7
	MessageType_INSTANCE_NOT_FOUND    MessageType = 8
	MessageType_INSTANCE_NOT_STOPPED  MessageType = 9
	MessageType_INSTANCE_NOT_STARTED  MessageType = 10
	MessageType_ERROR_BUILDING_CONFIG MessageType = 11
	MessageType_ERROR_PARSING_CONFIG  MessageType = 12
	MessageType_ERROR_READING_CONFIG  MessageType = 13
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "EMPTY",
		1:  "EMPTY_CONFIGURATION",
		2:  "START_COMMAND_SERVER",
		3:  "CREATE_SERVICE",
		4:  "START_SERVICE",
		5:  "UNEXPECTED_ERROR",
		6:  "ALREADY_STARTED",
		7:  "ALREADY_STOPPED",
		8:  "INSTANCE_NOT_FOUND",
		9:  "INSTANCE_NOT_STOPPED",
		10: "INSTANCE_NOT_STARTED",
		11: "ERROR_BUILDING_CONFIG",
		12: "ERROR_PARSING_CONFIG",
		13: "ERROR_READING_CONFIG",
	}
	MessageType_value = map[string]int32{
		"EMPTY":                 0,
		"EMPTY_CONFIGURATION":   1,
		"START_COMMAND_SERVER":  2,
		"CREATE_SERVICE":        3,
		"START_SERVICE":         4,
		"UNEXPECTED_ERROR":      5,
		"ALREADY_STARTED":       6,
		"ALREADY_STOPPED":       7,
		"INSTANCE_NOT_FOUND":    8,
		"INSTANCE_NOT_STOPPED":  9,
		"INSTANCE_NOT_STARTED":  10,
		"ERROR_BUILDING_CONFIG": 11,
		"ERROR_PARSING_CONFIG":  12,
		"ERROR_READING_CONFIG":  13,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_hiddify_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_hiddify_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{1}
}

type LogLevel int32

const (
	LogLevel_DEBUG   LogLevel = 0
	LogLevel_INFO    LogLevel = 1
	LogLevel_WARNING LogLevel = 2
	LogLevel_ERROR   LogLevel = 3
	LogLevel_FATAL   LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
		4: "FATAL",
	}
	LogLevel_value = map[string]int32{
		"DEBUG":   0,
		"INFO":    1,
		"WARNING": 2,
		"ERROR":   3,
		"FATAL":   4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_hiddify_proto_enumTypes[2].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_hiddify_proto_enumTypes[2]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{2}
}

type LogType int32

const (
	LogType_CORE    LogType = 0
	LogType_SERVICE LogType = 1
	LogType_CONFIG  LogType = 2
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "CORE",
		1: "SERVICE",
		2: "CONFIG",
	}
	LogType_value = map[string]int32{
		"CORE":    0,
		"SERVICE": 1,
		"CONFIG":  2,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_hiddify_proto_enumTypes[3].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_hiddify_proto_enumTypes[3]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{3}
}

type CoreInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CoreState     CoreState              `protobuf:"varint,1,opt,name=core_state,json=coreState,proto3,enum=hiddifyrpc.CoreState" json:"core_state,omitempty"`
	MessageType   MessageType            `protobuf:"varint,2,opt,name=message_type,json=messageType,proto3,enum=hiddifyrpc.MessageType" json:"message_type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreInfoResponse) Reset() {
	*x = CoreInfoResponse{}
	mi := &file_hiddify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreInfoResponse) ProtoMessage() {}

func (x *CoreInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreInfoResponse.ProtoReflect.Descriptor instead.
func (*CoreInfoResponse) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{0}
}

func (x *CoreInfoResponse) GetCoreState() CoreState {
	if x != nil {
		return x.CoreState
	}
	return CoreState_STOPPED
}

func (x *CoreInfoResponse) GetMessageType() MessageType {
	if x != nil {
		return x.MessageType
	}
	return MessageType_EMPTY
}

func (x *CoreInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath             string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	ConfigContent          string                 `protobuf:"bytes,2,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"` // Optional if configPath is not provided.
	DisableMemoryLimit     bool                   `protobuf:"varint,3,opt,name=disable_memory_limit,json=disableMemoryLimit,proto3" json:"disable_memory_limit,omitempty"`
	DelayStart             bool                   `protobuf:"varint,4,opt,name=delay_start,json=delayStart,proto3" json:"delay_start,omitempty"`
	EnableOldCommandServer bool                   `protobuf:"varint,5,opt,name=enable_old_command_server,json=enableOldCommandServer,proto3" json:"enable_old_command_server,omitempty"`
	EnableRawConfig        bool                   `protobuf:"varint,6,opt,name=enable_raw_config,json=enableRawConfig,proto3" json:"enable_raw_config,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_hiddify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{1}
}

func (x *StartRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *StartRequest) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

func (x *StartRequest) GetDisableMemoryLimit() bool {
	if x != nil {
		return x.DisableMemoryLimit
	}
	return false
}

func (x *StartRequest) GetDelayStart() bool {
	if x != nil {
		return x.DelayStart
	}
	return false
}

func (x *StartRequest) GetEnableOldCommandServer() bool {
	if x != nil {
		return x.EnableOldCommandServer
	}
	return false
}

func (x *StartRequest) GetEnableRawConfig() bool {
	if x != nil {
		return x.EnableRawConfig
	}
	return false
}

type SetupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasePath      string                 `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	WorkingPath   string                 `protobuf:"bytes,2,opt,name=working_path,json=workingPath,proto3" json:"working_path,omitempty"`
	TempPath      string                 `protobuf:"bytes,3,opt,name=temp_path,json=tempPath,proto3" json:"temp_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupRequest) Reset() {
	*x = SetupRequest{}
	mi := &file_hiddify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupRequest) ProtoMessage() {}

func (x *SetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupRequest.ProtoReflect.Descriptor instead.
func (*SetupRequest) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{2}
}

func (x *SetupRequest) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

func (x *SetupRequest) GetWorkingPath() string {
	if x != nil {
		return x.WorkingPath
	}
	return ""
}

func (x *SetupRequest) GetTempPath() string {
	if x != nil {
		return x.TempPath
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseCode  ResponseCode           `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3,enum=hiddifyrpc.ResponseCode" json:"response_code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_hiddify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetResponseCode() ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return ResponseCode_OK
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SystemInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Memory           int64                  `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Goroutines       int32                  `protobuf:"varint,2,opt,name=goroutines,proto3" json:"goroutines,omitempty"`
	ConnectionsIn    int32                  `protobuf:"varint,3,opt,name=connections_in,json=connectionsIn,proto3" json:"connections_in,omitempty"`
	ConnectionsOut   int32                  `protobuf:"varint,4,opt,name=connections_out,json=connectionsOut,proto3" json:"connections_out,omitempty"`
	TrafficAvailable bool                   `protobuf:"varint,5,opt,name=traffic_available,json=trafficAvailable,proto3" json:"traffic_available,omitempty"`
	Uplink           int64                  `protobuf:"varint,6,opt,name=uplink,proto3" json:"uplink,omitempty"`
	Downlink         int64                  `protobuf:"varint,7,opt,name=downlink,proto3" json:"downlink,omitempty"`
	UplinkTotal      int64                  `protobuf:"varint,8,opt,name=uplink_total,json=uplinkTotal,proto3" json:"uplink_total,omitempty"`
	DownlinkTotal    int64                  `protobuf:"varint,9,opt,name=downlink_total,json=downlinkTotal,proto3" json:"downlink_total,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemInfo) Reset() {
	*x = SystemInfo{}
	mi := &file_hiddify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemInfo) ProtoMessage() {}

func (x *SystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemInfo.ProtoReflect.Descriptor instead.
func (*SystemInfo) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{4}
}

func (x *SystemInfo) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *SystemInfo) GetGoroutines() int32 {
	if x != nil {
		return x.Goroutines
	}
	return 0
}

func (x *SystemInfo) GetConnectionsIn() int32 {
	if x != nil {
		return x.ConnectionsIn
	}
	return 0
}

func (x *SystemInfo) GetConnectionsOut() int32 {
	if x != nil {
		return x.ConnectionsOut
	}
	return 0
}

func (x *SystemInfo) GetTrafficAvailable() bool {
	if x != nil {
		return x.TrafficAvailable
	}
	return false
}

func (x *SystemInfo) GetUplink() int64 {
	if x != nil {
		return x.Uplink
	}
	return 0
}

func (x *SystemInfo) GetDownlink() int64 {
	if x != nil {
		return x.Downlink
	}
	return 0
}

func (x *SystemInfo) GetUplinkTotal() int64 {
	if x != nil {
		return x.UplinkTotal
	}
	return 0
}

func (x *SystemInfo) GetDownlinkTotal() int64 {
	if x != nil {
		return x.DownlinkTotal
	}
	return 0
}

type OutboundGroupItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UrlTestTime   int64                  `protobuf:"varint,3,opt,name=url_test_time,json=urlTestTime,proto3" json:"url_test_time,omitempty"`
	UrlTestDelay  int32                  `protobuf:"varint,4,opt,name=url_test_delay,json=urlTestDelay,proto3" json:"url_test_delay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundGroupItem) Reset() {
	*x = OutboundGroupItem{}
	mi := &file_hiddify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundGroupItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundGroupItem) ProtoMessage() {}

func (x *OutboundGroupItem) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundGroupItem.ProtoReflect.Descriptor instead.
func (*OutboundGroupItem) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{5}
}

func (x *OutboundGroupItem) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutboundGroupItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutboundGroupItem) GetUrlTestTime() int64 {
	if x != nil {
		return x.UrlTestTime
	}
	return 0
}

func (x *OutboundGroupItem) GetUrlTestDelay() int32 {
	if x != nil {
		return x.UrlTestDelay
	}
	return 0
}

type OutboundGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Selected      string                 `protobuf:"bytes,3,opt,name=selected,proto3" json:"selected,omitempty"`
	Items         []*OutboundGroupItem   `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundGroup) Reset() {
	*x = OutboundGroup{}
	mi := &file_hiddify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundGroup) ProtoMessage() {}

func (x *OutboundGroup) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundGroup.ProtoReflect.Descriptor instead.
func (*OutboundGroup) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{6}
}

func (x *OutboundGroup) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *OutboundGroup) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutboundGroup) GetSelected() string {
	if x != nil {
		return x.Selected
	}
	return ""
}

func (x *OutboundGroup) GetItems() []*OutboundGroupItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OutboundGroupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OutboundGroup       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboundGroupList) Reset() {
	*x = OutboundGroupList{}
	mi := &file_hiddify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboundGroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundGroupList) ProtoMessage() {}

func (x *OutboundGroupList) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundGroupList.ProtoReflect.Descriptor instead.
func (*OutboundGroupList) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{7}
}

func (x *OutboundGroupList) GetItems() []*OutboundGroup {
	if x != nil {
		return x.Items
	}
	return nil
}

type SystemProxyStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Enabled       bool                   `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemProxyStatus) Reset() {
	*x = SystemProxyStatus{}
	mi := &file_hiddify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemProxyStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemProxyStatus) ProtoMessage() {}

func (x *SystemProxyStatus) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemProxyStatus.ProtoReflect.Descriptor instead.
func (*SystemProxyStatus) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{8}
}

func (x *SystemProxyStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *SystemProxyStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ParseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,2,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	TempPath      string                 `protobuf:"bytes,3,opt,name=temp_path,json=tempPath,proto3" json:"temp_path,omitempty"`
	Debug         bool                   `protobuf:"varint,4,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	mi := &file_hiddify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{9}
}

func (x *ParseRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ParseRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

func (x *ParseRequest) GetTempPath() string {
	if x != nil {
		return x.TempPath
	}
	return ""
}

func (x *ParseRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type ParseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseCode  ResponseCode           `protobuf:"varint,1,opt,name=response_code,json=responseCode,proto3,enum=hiddifyrpc.ResponseCode" json:"response_code,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	mi := &file_hiddify_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{10}
}

func (x *ParseResponse) GetResponseCode() ResponseCode {
	if x != nil {
		return x.ResponseCode
	}
	return ResponseCode_OK
}

func (x *ParseResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ParseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ChangeHiddifySettingsRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HiddifySettingsJson string                 `protobuf:"bytes,1,opt,name=hiddify_settings_json,json=hiddifySettingsJson,proto3" json:"hiddify_settings_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChangeHiddifySettingsRequest) Reset() {
	*x = ChangeHiddifySettingsRequest{}
	mi := &file_hiddify_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeHiddifySettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeHiddifySettingsRequest) ProtoMessage() {}

func (x *ChangeHiddifySettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeHiddifySettingsRequest.ProtoReflect.Descriptor instead.
func (*ChangeHiddifySettingsRequest) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeHiddifySettingsRequest) GetHiddifySettingsJson() string {
	if x != nil {
		return x.HiddifySettingsJson
	}
	return ""
}

type HiddifySettingsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HiddifySettingsJson string                 `protobuf:"bytes,1,opt,name=hiddify_settings_json,json=hiddifySettingsJson,proto3" json:"hiddify_settings_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *HiddifySettingsResponse) Reset() {
	*x = HiddifySettingsResponse{}
	mi := &file_hiddify_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiddifySettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddifySettingsResponse) ProtoMessage() {}

func (x *HiddifySettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddifySettingsResponse.ProtoReflect.Descriptor instead.
func (*HiddifySettingsResponse) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{12}
}

func (x *HiddifySettingsResponse) GetHiddifySettingsJson() string {
	if x != nil {
		return x.HiddifySettingsJson
	}
	return ""
}

type GenerateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	TempPath      string                 `protobuf:"bytes,2,opt,name=temp_path,json=tempPath,proto3" json:"temp_path,omitempty"`
	Debug         bool                   `protobuf:"varint,3,opt,name=debug,proto3" json:"debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateConfigRequest) Reset() {
	*x = GenerateConfigRequest{}
	mi := &file_hiddify_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfigRequest) ProtoMessage() {}

func (x *GenerateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfigRequest.ProtoReflect.Descriptor instead.
func (*GenerateConfigRequest) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{13}
}

func (x *GenerateConfigRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GenerateConfigRequest) GetTempPath() string {
	if x != nil {
		return x.TempPath
	}
	return ""
}

func (x *GenerateConfigRequest) GetDebug() bool {
	if x != nil {
		return x.Debug
	}
	return false
}

type GenerateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigContent string                 `protobuf:"bytes,1,opt,name=config_content,json=configContent,proto3" json:"config_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateConfigResponse) Reset() {
	*x = GenerateConfigResponse{}
	mi := &file_hiddify_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateConfigResponse) ProtoMessage() {}

func (x *GenerateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateConfigResponse.ProtoReflect.Descriptor instead.
func (*GenerateConfigResponse) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{14}
}

func (x *GenerateConfigResponse) GetConfigContent() string {
	if x != nil {
		return x.ConfigContent
	}
	return ""
}

type SelectOutboundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupTag      string                 `protobuf:"bytes,1,opt,name=group_tag,json=groupTag,proto3" json:"group_tag,omitempty"`
	OutboundTag   string                 `protobuf:"bytes,2,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectOutboundRequest) Reset() {
	*x = SelectOutboundRequest{}
	mi := &file_hiddify_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectOutboundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectOutboundRequest) ProtoMessage() {}

func (x *SelectOutboundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectOutboundRequest.ProtoReflect.Descriptor instead.
func (*SelectOutboundRequest) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{15}
}

func (x *SelectOutboundRequest) GetGroupTag() string {
	if x != nil {
		return x.GroupTag
	}
	return ""
}

func (x *SelectOutboundRequest) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

type UrlTestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupTag      string                 `protobuf:"bytes,1,opt,name=group_tag,json=groupTag,proto3" json:"group_tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlTestRequest) Reset() {
	*x = UrlTestRequest{}
	mi := &file_hiddify_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlTestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlTestRequest) ProtoMessage() {}

func (x *UrlTestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlTestRequest.ProtoReflect.Descriptor instead.
func (*UrlTestRequest) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{16}
}

func (x *UrlTestRequest) GetGroupTag() string {
	if x != nil {
		return x.GroupTag
	}
	return ""
}

type SetSystemProxyEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsEnabled     bool                   `protobuf:"varint,1,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSystemProxyEnabledRequest) Reset() {
	*x = SetSystemProxyEnabledRequest{}
	mi := &file_hiddify_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSystemProxyEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSystemProxyEnabledRequest) ProtoMessage() {}

func (x *SetSystemProxyEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSystemProxyEnabledRequest.ProtoReflect.Descriptor instead.
func (*SetSystemProxyEnabledRequest) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{17}
}

func (x *SetSystemProxyEnabledRequest) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

type ConfigCapabilityResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SupportsTlsFragment bool                   `protobuf:"varint,1,opt,name=supports_tls_fragment,json=supportsTlsFragment,proto3" json:"supports_tls_fragment,omitempty"`
	SupportsQuic        bool                   `protobuf:"varint,2,opt,name=supports_quic,json=supportsQuic,proto3" json:"supports_quic,omitempty"`
	SupportsEch         bool                   `protobuf:"varint,3,opt,name=supports_ech,json=supportsEch,proto3" json:"supports_ech,omitempty"`
	SchemaVersion       string                 `protobuf:"bytes,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ConfigCapabilityResponse) Reset() {
	*x = ConfigCapabilityResponse{}
	mi := &file_hiddify_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigCapabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigCapabilityResponse) ProtoMessage() {}

func (x *ConfigCapabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigCapabilityResponse.ProtoReflect.Descriptor instead.
func (*ConfigCapabilityResponse) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{18}
}

func (x *ConfigCapabilityResponse) GetSupportsTlsFragment() bool {
	if x != nil {
		return x.SupportsTlsFragment
	}
	return false
}

func (x *ConfigCapabilityResponse) GetSupportsQuic() bool {
	if x != nil {
		return x.SupportsQuic
	}
	return false
}

func (x *ConfigCapabilityResponse) GetSupportsEch() bool {
	if x != nil {
		return x.SupportsEch
	}
	return false
}

func (x *ConfigCapabilityResponse) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

type LogMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=hiddifyrpc.LogLevel" json:"level,omitempty"`
	Type          LogType                `protobuf:"varint,2,opt,name=type,proto3,enum=hiddifyrpc.LogType" json:"type,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogMessage) Reset() {
	*x = LogMessage{}
	mi := &file_hiddify_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMessage) ProtoMessage() {}

func (x *LogMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMessage.ProtoReflect.Descriptor instead.
func (*LogMessage) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{19}
}

func (x *LogMessage) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DEBUG
}

func (x *LogMessage) GetType() LogType {
	if x != nil {
		return x.Type
	}
	return LogType_CORE
}

func (x *LogMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_hiddify_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{20}
}

type TunnelStartRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Ipv6                   bool                   `protobuf:"varint,1,opt,name=ipv6,proto3" json:"ipv6,omitempty"`
	ServerPort             int32                  `protobuf:"varint,2,opt,name=server_port,json=serverPort,proto3" json:"server_port,omitempty"`
	StrictRoute            bool                   `protobuf:"varint,3,opt,name=strict_route,json=strictRoute,proto3" json:"strict_route,omitempty"`
	EndpointIndependentNat bool                   `protobuf:"varint,4,opt,name=endpoint_independent_nat,json=endpointIndependentNat,proto3" json:"endpoint_independent_nat,omitempty"`
	Stack                  string                 `protobuf:"bytes,5,opt,name=stack,proto3" json:"stack,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TunnelStartRequest) Reset() {
	*x = TunnelStartRequest{}
	mi := &file_hiddify_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelStartRequest) ProtoMessage() {}

func (x *TunnelStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelStartRequest.ProtoReflect.Descriptor instead.
func (*TunnelStartRequest) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{21}
}

func (x *TunnelStartRequest) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

func (x *TunnelStartRequest) GetServerPort() int32 {
	if x != nil {
		return x.ServerPort
	}
	return 0
}

func (x *TunnelStartRequest) GetStrictRoute() bool {
	if x != nil {
		return x.StrictRoute
	}
	return false
}

func (x *TunnelStartRequest) GetEndpointIndependentNat() bool {
	if x != nil {
		return x.EndpointIndependentNat
	}
	return false
}

func (x *TunnelStartRequest) GetStack() string {
	if x != nil {
		return x.Stack
	}
	return ""
}

type TunnelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelResponse) Reset() {
	*x = TunnelResponse{}
	mi := &file_hiddify_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelResponse) ProtoMessage() {}

func (x *TunnelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hiddify_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelResponse.ProtoReflect.Descriptor instead.
func (*TunnelResponse) Descriptor() ([]byte, []int) {
	return file_hiddify_proto_rawDescGZIP(), []int{22}
}

func (x *TunnelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hiddify_proto protoreflect.FileDescriptor

const file_hiddify_proto_rawDesc = "" +
	"\n" +
	"\rhiddify.proto\x12\n" +
	"hiddifyrpc\x1a\n" +
	"base.proto\"\x9e\x01\n" +
	"\x10CoreInfoResponse\x124\n" +
	"\n" +
	"core_state\x18\x01 \x01(\x0e2\x15.hiddifyrpc.CoreStateR\tcoreState\x12:\n" +
	"\fmessage_type\x18\x02 \x01(\x0e2\x17.hiddifyrpc.MessageTypeR\vmessageType\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x90\x02\n" +
	"\fStartRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\x12%\n" +
	"\x0econfig_content\x18\x02 \x01(\tR\rconfigContent\x120\n" +
	"\x14disable_memory_limit\x18\x03 \x01(\bR\x12disableMemoryLimit\x12\x1f\n" +
	"\vdelay_start\x18\x04 \x01(\bR\n" +
	"delayStart\x129\n" +
	"\x19enable_old_command_server\x18\x05 \x01(\bR\x16enableOldCommandServer\x12*\n" +
	"\x11enable_raw_config\x18\x06 \x01(\bR\x0fenableRawConfig\"k\n" +
	"\fSetupRequest\x12\x1b\n" +
	"\tbase_path\x18\x01 \x01(\tR\bbasePath\x12!\n" +
	"\fworking_path\x18\x02 \x01(\tR\vworkingPath\x12\x1b\n" +
	"\ttemp_path\x18\x03 \x01(\tR\btempPath\"c\n" +
	"\bResponse\x12=\n" +
	"\rresponse_code\x18\x01 \x01(\x0e2\x18.hiddifyrpc.ResponseCodeR\fresponseCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbf\x02\n" +
	"\n" +
	"SystemInfo\x12\x16\n" +
	"\x06memory\x18\x01 \x01(\x03R\x06memory\x12\x1e\n" +
	"\n" +
	"goroutines\x18\x02 \x01(\x05R\n" +
	"goroutines\x12%\n" +
	"\x0econnections_in\x18\x03 \x01(\x05R\rconnectionsIn\x12'\n" +
	"\x0fconnections_out\x18\x04 \x01(\x05R\x0econnectionsOut\x12+\n" +
	"\x11traffic_available\x18\x05 \x01(\bR\x10trafficAvailable\x12\x16\n" +
	"\x06uplink\x18\x06 \x01(\x03R\x06uplink\x12\x1a\n" +
	"\bdownlink\x18\a \x01(\x03R\bdownlink\x12!\n" +
	"\fuplink_total\x18\b \x01(\x03R\vuplinkTotal\x12%\n" +
	"\x0edownlink_total\x18\t \x01(\x03R\rdownlinkTotal\"\x83\x01\n" +
	"\x11OutboundGroupItem\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\"\n" +
	"\rurl_test_time\x18\x03 \x01(\x03R\vurlTestTime\x12$\n" +
	"\x0eurl_test_delay\x18\x04 \x01(\x05R\furlTestDelay\"\x86\x01\n" +
	"\rOutboundGroup\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bselected\x18\x03 \x01(\tR\bselected\x123\n" +
	"\x05items\x18\x04 \x03(\v2\x1d.hiddifyrpc.OutboundGroupItemR\x05items\"D\n" +
	"\x11OutboundGroupList\x12/\n" +
	"\x05items\x18\x01 \x03(\v2\x19.hiddifyrpc.OutboundGroupR\x05items\"K\n" +
	"\x11SystemProxyStatus\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"|\n" +
	"\fParseRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x1f\n" +
	"\vconfig_path\x18\x02 \x01(\tR\n" +
	"configPath\x12\x1b\n" +
	"\ttemp_path\x18\x03 \x01(\tR\btempPath\x12\x14\n" +
	"\x05debug\x18\x04 \x01(\bR\x05debug\"\x82\x01\n" +
	"\rParseResponse\x12=\n" +
	"\rresponse_code\x18\x01 \x01(\x0e2\x18.hiddifyrpc.ResponseCodeR\fresponseCode\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"R\n" +
	"\x1cChangeHiddifySettingsRequest\x122\n" +
	"\x15hiddify_settings_json\x18\x01 \x01(\tR\x13hiddifySettingsJson\"M\n" +
	"\x17HiddifySettingsResponse\x122\n" +
	"\x15hiddify_settings_json\x18\x01 \x01(\tR\x13hiddifySettingsJson\"^\n" +
	"\x15GenerateConfigRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\ttemp_path\x18\x02 \x01(\tR\btempPath\x12\x14\n" +
	"\x05debug\x18\x03 \x01(\bR\x05debug\"?\n" +
	"\x16GenerateConfigResponse\x12%\n" +
	"\x0econfig_content\x18\x01 \x01(\tR\rconfigContent\"W\n" +
	"\x15SelectOutboundRequest\x12\x1b\n" +
	"\tgroup_tag\x18\x01 \x01(\tR\bgroupTag\x12!\n" +
	"\foutbound_tag\x18\x02 \x01(\tR\voutboundTag\"-\n" +
	"\x0eUrlTestRequest\x12\x1b\n" +
	"\tgroup_tag\x18\x01 \x01(\tR\bgroupTag\"=\n" +
	"\x1cSetSystemProxyEnabledRequest\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x01 \x01(\bR\tisEnabled\"\xbd\x01\n" +
	"\x18ConfigCapabilityResponse\x122\n" +
	"\x15supports_tls_fragment\x18\x01 \x01(\bR\x13supportsTlsFragment\x12#\n" +
	"\rsupports_quic\x18\x02 \x01(\bR\fsupportsQuic\x12!\n" +
	"\fsupports_ech\x18\x03 \x01(\bR\vsupportsEch\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\tR\rschemaVersion\"{\n" +
	"\n" +
	"LogMessage\x12*\n" +
	"\x05level\x18\x01 \x01(\x0e2\x14.hiddifyrpc.LogLevelR\x05level\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.hiddifyrpc.LogTypeR\x04type\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\r\n" +
	"\vStopRequest\"\xbc\x01\n" +
	"\x12TunnelStartRequest\x12\x12\n" +
	"\x04ipv6\x18\x01 \x01(\bR\x04ipv6\x12\x1f\n" +
	"\vserver_port\x18\x02 \x01(\x05R\n" +
	"serverPort\x12!\n" +
	"\fstrict_route\x18\x03 \x01(\bR\vstrictRoute\x128\n" +
	"\x18endpoint_independent_nat\x18\x04 \x01(\bR\x16endpointIndependentNat\x12\x14\n" +
	"\x05stack\x18\x05 \x01(\tR\x05stack\"*\n" +
	"\x0eTunnelResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*A\n" +
	"\tCoreState\x12\v\n" +
	"\aSTOPPED\x10\x00\x12\f\n" +
	"\bSTARTING\x10\x01\x12\v\n" +
	"\aSTARTED\x10\x02\x12\f\n" +
	"\bSTOPPING\x10\x03*\xcd\x02\n" +
	"\vMessageType\x12\t\n" +
	"\x05EMPTY\x10\x00\x12\x17\n" +
	"\x13EMPTY_CONFIGURATION\x10\x01\x12\x18\n" +
	"\x14START_COMMAND_SERVER\x10\x02\x12\x12\n" +
	"\x0eCREATE_SERVICE\x10\x03\x12\x11\n" +
	"\rSTART_SERVICE\x10\x04\x12\x14\n" +
	"\x10UNEXPECTED_ERROR\x10\x05\x12\x13\n" +
	"\x0fALREADY_STARTED\x10\x06\x12\x13\n" +
	"\x0fALREADY_STOPPED\x10\a\x12\x16\n" +
	"\x12INSTANCE_NOT_FOUND\x10\b\x12\x18\n" +
	"\x14INSTANCE_NOT_STOPPED\x10\t\x12\x18\n" +
	"\x14INSTANCE_NOT_STARTED\x10\n" +
	"\x12\x19\n" +
	"\x15ERROR_BUILDING_CONFIG\x10\v\x12\x18\n" +
	"\x14ERROR_PARSING_CONFIG\x10\f\x12\x18\n" +
	"\x14ERROR_READING_CONFIG\x10\r*B\n" +
	"\bLogLevel\x12\t\n" +
	"\x05DEBUG\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\t\n" +
	"\x05FATAL\x10\x04*,\n" +
	"\aLogType\x12\b\n" +
	"\x04CORE\x10\x00\x12\v\n" +
	"\aSERVICE\x10\x01\x12\n" +
	"\n" +
	"\x06CONFIG\x10\x022\x93\x01\n" +
	"\x05Hello\x12?\n" +
	"\bSayHello\x12\x18.hiddifyrpc.HelloRequest\x1a\x19.hiddifyrpc.HelloResponse\x12I\n" +
	"\x0eSayHelloStream\x12\x18.hiddifyrpc.HelloRequest\x1a\x19.hiddifyrpc.HelloResponse(\x010\x012\xfd\t\n" +
	"\x04Core\x12?\n" +
	"\x05Start\x12\x18.hiddifyrpc.StartRequest\x1a\x1c.hiddifyrpc.CoreInfoResponse\x12E\n" +
	"\x10CoreInfoListener\x12\x11.hiddifyrpc.Empty\x1a\x1c.hiddifyrpc.CoreInfoResponse0\x01\x12C\n" +
	"\rOutboundsInfo\x12\x11.hiddifyrpc.Empty\x1a\x1d.hiddifyrpc.OutboundGroupList0\x01\x12G\n" +
	"\x11MainOutboundsInfo\x12\x11.hiddifyrpc.Empty\x1a\x1d.hiddifyrpc.OutboundGroupList0\x01\x12<\n" +
	"\rGetSystemInfo\x12\x11.hiddifyrpc.Empty\x1a\x16.hiddifyrpc.SystemInfo0\x01\x127\n" +
	"\x05Setup\x12\x18.hiddifyrpc.SetupRequest\x1a\x14.hiddifyrpc.Response\x12<\n" +
	"\x05Parse\x12\x18.hiddifyrpc.ParseRequest\x1a\x19.hiddifyrpc.ParseResponse\x12_\n" +
	"\x15ChangeHiddifySettings\x12(.hiddifyrpc.ChangeHiddifySettingsRequest\x1a\x1c.hiddifyrpc.CoreInfoResponse\x12L\n" +
	"\x12GetHiddifySettings\x12\x11.hiddifyrpc.Empty\x1a#.hiddifyrpc.HiddifySettingsResponse\x12F\n" +
	"\fStartService\x12\x18.hiddifyrpc.StartRequest\x1a\x1c.hiddifyrpc.CoreInfoResponse\x127\n" +
	"\x04Stop\x12\x11.hiddifyrpc.Empty\x1a\x1c.hiddifyrpc.CoreInfoResponse\x12A\n" +
	"\aRestart\x12\x18.hiddifyrpc.StartRequest\x1a\x1c.hiddifyrpc.CoreInfoResponse\x12I\n" +
	"\x0eSelectOutbound\x12!.hiddifyrpc.SelectOutboundRequest\x1a\x14.hiddifyrpc.Response\x12;\n" +
	"\aUrlTest\x12\x1a.hiddifyrpc.UrlTestRequest\x1a\x14.hiddifyrpc.Response\x12H\n" +
	"\x14GetSystemProxyStatus\x12\x11.hiddifyrpc.Empty\x1a\x1d.hiddifyrpc.SystemProxyStatus\x12W\n" +
	"\x15SetSystemProxyEnabled\x12(.hiddifyrpc.SetSystemProxyEnabledRequest\x1a\x14.hiddifyrpc.Response\x12P\n" +
	"\x15GetConfigCapabilities\x12\x11.hiddifyrpc.Empty\x1a$.hiddifyrpc.ConfigCapabilityResponse\x12:\n" +
	"\vLogListener\x12\x11.hiddifyrpc.Empty\x1a\x16.hiddifyrpc.LogMessage0\x012\xfb\x01\n" +
	"\rTunnelService\x12C\n" +
	"\x05Start\x12\x1e.hiddifyrpc.TunnelStartRequest\x1a\x1a.hiddifyrpc.TunnelResponse\x125\n" +
	"\x04Stop\x12\x11.hiddifyrpc.Empty\x1a\x1a.hiddifyrpc.TunnelResponse\x127\n" +
	"\x06Status\x12\x11.hiddifyrpc.Empty\x1a\x1a.hiddifyrpc.TunnelResponse\x125\n" +
	"\x04Exit\x12\x11.hiddifyrpc.Empty\x1a\x1a.hiddifyrpc.TunnelResponseB\x0eZ\f./hiddifyrpcb\x06proto3"

var (
	file_hiddify_proto_rawDescOnce sync.Once
	file_hiddify_proto_rawDescData []byte
)

func file_hiddify_proto_rawDescGZIP() []byte {
	file_hiddify_proto_rawDescOnce.Do(func() {
		file_hiddify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hiddify_proto_rawDesc), len(file_hiddify_proto_rawDesc)))
	})
	return file_hiddify_proto_rawDescData
}

var file_hiddify_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_hiddify_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_hiddify_proto_goTypes = []any{
	(CoreState)(0),                       // 0: hiddifyrpc.CoreState
	(MessageType)(0),                     // 1: hiddifyrpc.MessageType
	(LogLevel)(0),                        // 2: hiddifyrpc.LogLevel
	(LogType)(0),                         // 3: hiddifyrpc.LogType
	(*CoreInfoResponse)(nil),             // 4: hiddifyrpc.CoreInfoResponse
	(*StartRequest)(nil),                 // 5: hiddifyrpc.StartRequest
	(*SetupRequest)(nil),                 // 6: hiddifyrpc.SetupRequest
	(*Response)(nil),                     // 7: hiddifyrpc.Response
	(*SystemInfo)(nil),                   // 8: hiddifyrpc.SystemInfo
	(*OutboundGroupItem)(nil),            // 9: hiddifyrpc.OutboundGroupItem
	(*OutboundGroup)(nil),                // 10: hiddifyrpc.OutboundGroup
	(*OutboundGroupList)(nil),            // 11: hiddifyrpc.OutboundGroupList
	(*SystemProxyStatus)(nil),            // 12: hiddifyrpc.SystemProxyStatus
	(*ParseRequest)(nil),                 // 13: hiddifyrpc.ParseRequest
	(*ParseResponse)(nil),                // 14: hiddifyrpc.ParseResponse
	(*ChangeHiddifySettingsRequest)(nil), // 15: hiddifyrpc.ChangeHiddifySettingsRequest
	(*HiddifySettingsResponse)(nil),      // 16: hiddifyrpc.HiddifySettingsResponse
	(*GenerateConfigRequest)(nil),        // 17: hiddifyrpc.GenerateConfigRequest
	(*GenerateConfigResponse)(nil),       // 18: hiddifyrpc.GenerateConfigResponse
	(*SelectOutboundRequest)(nil),        // 19: hiddifyrpc.SelectOutboundRequest
	(*UrlTestRequest)(nil),               // 20: hiddifyrpc.UrlTestRequest
	(*SetSystemProxyEnabledRequest)(nil), // 21: hiddifyrpc.SetSystemProxyEnabledRequest
	(*ConfigCapabilityResponse)(nil),     // 22: hiddifyrpc.ConfigCapabilityResponse
	(*LogMessage)(nil),                   // 23: hiddifyrpc.LogMessage
	(*StopRequest)(nil),                  // 24: hiddifyrpc.StopRequest
	(*TunnelStartRequest)(nil),           // 25: hiddifyrpc.TunnelStartRequest
	(*TunnelResponse)(nil),               // 26: hiddifyrpc.TunnelResponse
	(ResponseCode)(0),                    // 27: hiddifyrpc.ResponseCode
	(*HelloRequest)(nil),                 // 28: hiddifyrpc.HelloRequest
	(*Empty)(nil),                        // 29: hiddifyrpc.Empty
	(*HelloResponse)(nil),                // 30: hiddifyrpc.HelloResponse
}
var file_hiddify_proto_depIdxs = []int32{
	0,  // 0: hiddifyrpc.CoreInfoResponse.core_state:type_name -> hiddifyrpc.CoreState
	1,  // 1: hiddifyrpc.CoreInfoResponse.message_type:type_name -> hiddifyrpc.MessageType
	27, // 2: hiddifyrpc.Response.response_code:type_name -> hiddifyrpc.ResponseCode
	9,  // 3: hiddifyrpc.OutboundGroup.items:type_name -> hiddifyrpc.OutboundGroupItem
	10, // 4: hiddifyrpc.OutboundGroupList.items:type_name -> hiddifyrpc.OutboundGroup
	27, // 5: hiddifyrpc.ParseResponse.response_code:type_name -> hiddifyrpc.ResponseCode
	2,  // 6: hiddifyrpc.LogMessage.level:type_name -> hiddifyrpc.LogLevel
	3,  // 7: hiddifyrpc.LogMessage.type:type_name -> hiddifyrpc.LogType
	28, // 8: hiddifyrpc.Hello.SayHello:input_type -> hiddifyrpc.HelloRequest
	28, // 9: hiddifyrpc.Hello.SayHelloStream:input_type -> hiddifyrpc.HelloRequest
	5,  // 10: hiddifyrpc.Core.Start:input_type -> hiddifyrpc.StartRequest
	29, // 11: hiddifyrpc.Core.CoreInfoListener:input_type -> hiddifyrpc.Empty
	29, // 12: hiddifyrpc.Core.OutboundsInfo:input_type -> hiddifyrpc.Empty
	29, // 13: hiddifyrpc.Core.MainOutboundsInfo:input_type -> hiddifyrpc.Empty
	29, // 14: hiddifyrpc.Core.GetSystemInfo:input_type -> hiddifyrpc.Empty
	6,  // 15: hiddifyrpc.Core.Setup:input_type -> hiddifyrpc.SetupRequest
	13, // 16: hiddifyrpc.Core.Parse:input_type -> hiddifyrpc.ParseRequest
	15, // 17: hiddifyrpc.Core.ChangeHiddifySettings:input_type -> hiddifyrpc.ChangeHiddifySettingsRequest
	29, // 18: hiddifyrpc.Core.GetHiddifySettings:input_type -> hiddifyrpc.Empty
	5,  // 19: hiddifyrpc.Core.StartService:input_type -> hiddifyrpc.StartRequest
	29, // 20: hiddifyrpc.Core.Stop:input_type -> hiddifyrpc.Empty
	5,  // 21: hiddifyrpc.Core.Restart:input_type -> hiddifyrpc.StartRequest
	19, // 22: hiddifyrpc.Core.SelectOutbound:input_type -> hiddifyrpc.SelectOutboundRequest
	20, // 23: hiddifyrpc.Core.UrlTest:input_type -> hiddifyrpc.UrlTestRequest
	29, // 24: hiddifyrpc.Core.GetSystemProxyStatus:input_type -> hiddifyrpc.Empty
	21, // 25: hiddifyrpc.Core.SetSystemProxyEnabled:input_type -> hiddifyrpc.SetSystemProxyEnabledRequest
	29, // 26: hiddifyrpc.Core.GetConfigCapabilities:input_type -> hiddifyrpc.Empty
	29, // 27: hiddifyrpc.Core.LogListener:input_type -> hiddifyrpc.Empty
	25, // 28: hiddifyrpc.TunnelService.Start:input_type -> hiddifyrpc.TunnelStartRequest
	29, // 29: hiddifyrpc.TunnelService.Stop:input_type -> hiddifyrpc.Empty
	29, // 30: hiddifyrpc.TunnelService.Status:input_type -> hiddifyrpc.Empty
	29, // 31: hiddifyrpc.TunnelService.Exit:input_type -> hiddifyrpc.Empty
	30, // 32: hiddifyrpc.Hello.SayHello:output_type -> hiddifyrpc.HelloResponse
	30, // 33: hiddifyrpc.Hello.SayHelloStream:output_type -> hiddifyrpc.HelloResponse
	4,  // 34: hiddifyrpc.Core.Start:output_type -> hiddifyrpc.CoreInfoResponse
	4,  // 35: hiddifyrpc.Core.CoreInfoListener:output_type -> hiddifyrpc.CoreInfoResponse
	11, // 36: hiddifyrpc.Core.OutboundsInfo:output_type -> hiddifyrpc.OutboundGroupList
	11, // 37: hiddifyrpc.Core.MainOutboundsInfo:output_type -> hiddifyrpc.OutboundGroupList
	8,  // 38: hiddifyrpc.Core.GetSystemInfo:output_type -> hiddifyrpc.SystemInfo
	7,  // 39: hiddifyrpc.Core.Setup:output_type -> hiddifyrpc.Response
	14, // 40: hiddifyrpc.Core.Parse:output_type -> hiddifyrpc.ParseResponse
	4,  // 41: hiddifyrpc.Core.ChangeHiddifySettings:output_type -> hiddifyrpc.CoreInfoResponse
	16, // 42: hiddifyrpc.Core.GetHiddifySettings:output_type -> hiddifyrpc.HiddifySettingsResponse
	4,  // 43: hiddifyrpc.Core.StartService:output_type -> hiddifyrpc.CoreInfoResponse
	4,  // 44: hiddifyrpc.Core.Stop:output_type -> hiddifyrpc.CoreInfoResponse
	4,  // 45: hiddifyrpc.Core.Restart:output_type -> hiddifyrpc.CoreInfoResponse
	7,  // 46: hiddifyrpc.Core.SelectOutbound:output_type -> hiddifyrpc.Response
	7,  // 47: hiddifyrpc.Core.UrlTest:output_type -> hiddifyrpc.Response
	12, // 48: hiddifyrpc.Core.GetSystemProxyStatus:output_type -> hiddifyrpc.SystemProxyStatus
	7,  // 49: hiddifyrpc.Core.SetSystemProxyEnabled:output_type -> hiddifyrpc.Response
	22, // 50: hiddifyrpc.Core.GetConfigCapabilities:output_type -> hiddifyrpc.ConfigCapabilityResponse
	23, // 51: hiddifyrpc.Core.LogListener:output_type -> hiddifyrpc.LogMessage
	26, // 52: hiddifyrpc.TunnelService.Start:output_type -> hiddifyrpc.TunnelResponse
	26, // 53: hiddifyrpc.TunnelService.Stop:output_type -> hiddifyrpc.TunnelResponse
	26, // 54: hiddifyrpc.TunnelService.Status:output_type -> hiddifyrpc.TunnelResponse
	26, // 55: hiddifyrpc.TunnelService.Exit:output_type -> hiddifyrpc.TunnelResponse
	32, // [32:56] is the sub-list for method output_type
	8,  // [8:32] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_hiddify_proto_init() }
func file_hiddify_proto_init() {
	if File_hiddify_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hiddify_proto_rawDesc), len(file_hiddify_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_hiddify_proto_goTypes,
		DependencyIndexes: file_hiddify_proto_depIdxs,
		EnumInfos:         file_hiddify_proto_enumTypes,
		MessageInfos:      file_hiddify_proto_msgTypes,
	}.Build()
	File_hiddify_proto = out.File
	file_hiddify_proto_goTypes = nil
	file_hiddify_proto_depIdxs = nil
}
